spring:
  spring:
    mvc:
      throw-exception-if-no-handler-found: true

  datasource:
    url: jdbc:mysql://localhost:3306/mooko-database?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: mooko-admin
    password: mooko-admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 10
      idleTimeout: 300
      maxLifeTime: 300
      data-source-properties:
        rewriteBatchedStatements: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        use_sql_comments: true

  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 0bcc5773a6c07d341036ecb7c393013f
            client-secret: rhdZpPEWRvVMjIyvC4B1FBPhOU6gtUvh
            scope:
              - profile_nickname
            client-name: kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  cloud:
    aws:
      s3:
        endpoint: https://s3.ap-northeast-2.amazonaws.com/mooko-bucket
        region: ap-northeast-2

jwt:
  secret-Key: asdfasdfasdfasdrt123a1241qwetqpknapilugipk1j23k4lhj1adfkj9312kl3nasdkflj9Nvlnyasdfakljf891023jhlkasdf91nkhldf91kjlas90dfjl1k29azalikdjf912kjl3lasd9f0j1kl239asdjlkf
  access-token-expire-period: 7200      #2시간
  refresh-token-expire-period: 1209600  #2주



#  cloud:
#    aws:
#      s3:
#        endpoint: https://s3.ap-northeast-2.amazonaws.com
#        region: ap-northeast-2
#        bucket: mooko-bucket
#        profile-img: profile_img/
#        barcode: barcode/
#        thumbnail: thumbnail/
#        day: day/
#        event: event/
#        default-img: https://mooko-bucket.s3.ap-northeast-2.amazonaws.com/profile_img/default_img.png
#
#      region:
#        static: ap-northeast-2
#        auto: false
#
#      stack:
#        auto: false
#
#      credentials:
#        access-key: AKIAZASRWGR377OI4QVF
#        secret-key: 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